config/routes.rb
R12Team459::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  match "dashboard" => "dashboard#index", as: :dashboard
  match "explore" => "dashboard#explore", as: :explore

  resources :entries do
    collection do
      get :search
    end
  end
  resources :categories
  resources :user_entries
  root to: 'pages#home'
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :user_entries
  has_many :entries, through: :user_entries

  scope :search_for, ->(query) do
    return [] if query.empty?
    quoted = "%#{query}%"
    where("name like ?", quoted).uniq
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  self.inheritance_column = :must_be_type_but_we_not_use_sti

  belongs_to :user
  attr_accessible :description, :shareable, :url, :title, :type, :user_entries, :user_id
  has_many :user_entries, dependent: :destroy
  has_many :categories, through: :user_entries
  # attr_protected :type
  after_initialize :determinate_type

  accepts_nested_attributes_for :categories

  default_scope order: "entries.id DESC"

  scope :search_for, ->(query) do
    return [] if query.empty?
    quoted = "%#{query}%"
    where("url LIKE ? OR (title LIKE ? OR (description LIKE ?)) ", quoted, quoted, quoted).uniq
  end

  def to_hash
    {
      id: id,
      title: title,
      url: url,
      type: type,
      category_ids: category_ids,
      description: description
    }
  end

  def self.types
    @types ||= [Gist.new, Gem.new, Screencast.new, Article.new]
  end

  protected

  class Type
    def to_s; self.class.name.demodulize.underscore; end
    def match(uri)
      domains.map{ |d| uri.to_s.match(%r[^https?://#{d}.*]).nil? ? false : true }.any?
    end
    private
    def domains
      @domains ||= []
    end
  end

  class Gist < Type
    private
    def domains
      @domains ||= %w(gist.github.com)
    end
  end

  class Gem < Type
    private
    def domains
      @domains ||= %w(github.com rubygems.org)
    end
  end

  class Screencast < Type
    private
    def domains
      @domains ||= [
        'railscasts.com',
        'railsforzombies.org',
        'rubyonrails.org/screencasts/rails3',
        'peepcode.com',
        'pragprog.com/screencasts'
      ]
    end
  end

  class Article < Type
    def match(_); true; end
  end

  def determinate_type
    if self.new_record? && !self.type.present?
      self.type = self.class.types.select{|tp| tp.match(self.url) }.first.to_s
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable,:registerable, :recoverable, :validatable
  devise :database_authenticatable, :rememberable, :trackable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :provider, :uid, :name, :nickname, :avatar_url
  # attr_accessible :title, :body

  scope :find_by_auth, ->(auth) { where(provider: auth.provider, uid: auth.uid) }

  has_many :all_entries, class_name: 'Entry'
  has_many :entries, include: :categories, through: :user_entries
  has_many :user_entries
  has_many :categories, through: :user_entries, uniq: true

  def entries_for_category(category)
    entries.merge(categories.where(id: category.id))
  end

  (Entry.types || []).each do |type|
    define_method(type.to_s.pluralize) { entries.where(type: type.to_s).uniq }
  end

  def self.create_from_auth(auth)
    args = {
      name: auth.info.name,
      nickname: auth.info.nickname,
      provider: auth.provider,
      uid: auth.uid,
      email: auth.info.email,
      avatar_url: auth.info.image,
      password: Devise.friendly_token[0,20]
    }
    User.create(args)
  end

  def nick_and_name
    n = ''
    n << nickname if nickname.present?
    n << " (#{name})" if name.present?
    n.present? ? n : 'Unknown person'
  end
end

app/models/user_entry.rb
class UserEntry < ActiveRecord::Base
  belongs_to :user
  belongs_to :entry
  belongs_to :category
  attr_accessible :category_id, :entry_id, :user_id
  scope :for_category, ->(category) { where(category_id: category.id) }

  # accepts_nested_attributes_for :category, :entry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || resource.is_a?(User) ? dashboard_path : super
  end

end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  respond_to :json
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    @recent = {
      gems: current_user.gems.limit(5),
      gists: current_user.gists.limit(5),
      screencasts: current_user.screencasts.limit(5),
      articles: current_user.articles.limit(5),
    }
  end

  def explore
    @categories = current_user.categories.order("name ASC")
    @entries = current_user.user_entries.includes(:entry).where('user_entries.category_id' => @categories.map{|c| c.id})
  end
end

app/controllers/entries_controller.rb
require 'unicode_utils'

class EntriesController < InheritedResources::Base
  before_filter :authenticate_user!
  respond_to :json

  before_filter :prepare_create_params, only: :create

  def search
    query = URI.unescape(params[:q] || "")

    status, type, content = if query.uri? && current_user.entries.find_by_url(query).nil?
      [404, "link", current_user.entries.new(url: query)]
    else
      cat_ids = current_user.categories.search_for(query).map(&:id)
      results = current_user.entries.search_for(query).map(&:to_hash)
      from_categores = current_user.entries.where('user_entries.category_id' => cat_ids).map(&:to_hash)

      [200, "results", (results + from_categores).uniq]
    end

    respond_with({ status: status, type: type, content: content })
  end

  def prepare_create_params
    params[:entry][:user_id] = current_user.id
    cats = UnicodeUtils.downcase(params[:entry].delete(:categories)).split(',').map(&:strip).map do|name|
      current_user.categories.find_or_create_by_name(name)
    end
    params[:entry][:user_entries] = cats.map do |c|
      UserEntry.new(category_id: c.id, user_id: current_user.id)
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/user_entries_controller.rb
require 'unicode_utils'

class UserEntriesController < InheritedResources::Base
  before_filter :authenticate_user!

  respond_to :json

  def create
    params[:user_entry][:user_id] = current_user.id
    entry = params[:user_entry]
    if entry[:categories].present?
      categories = UnicodeUtils.downcase(entry[:categories]).split(',').map(&:strip).map do |name|
        current_user.categories.find_or_create_by_name(name).id
      end
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    auth = request.env["omniauth.auth"]

    @user = User.find_by_auth(auth).first
    @user = User.create_from_auth(auth) unless @user

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.github_data"] = auth
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def svg_tag(src)
    %Q{<object class="placeholder" data="/assets/#{src}.svg" type="image/svg+xml"></object>}.html_safe
  end
  def entry_link_to(entry)
    # = link_to user_entry.entry.title, user_entry.entry.url
    %Q{<a href="#{user_entry.entry.url}">#{user_entry.entry.title}</a>}
  end
end

app/views/dashboard/_entries.html.haml
- if entries.any?
  %dl= render partial: "dashboard/entry", collection: entries
- else
  %p.lead.muted No entries

app/views/dashboard/_entry.html.haml
.entry
  %dt
    = link_to entry.title, entry.url
    = link_to entry, method: :delete, remote: true, class: "close entry-destroy-link" do
      &times;
  %dd
    = entry.description
    %small= entry.categories.uniq.map{|c| c.name}.join(", ")

app/views/dashboard/_recent.html.haml
%h2 Recently added
.row.entries.dashboard
  - Entry.types.each do |type|
    .span3
      %h3= type.to_s.capitalize
      = render partial: "dashboard/entries", locals: { entries: @recent[type.to_s.pluralize.to_sym] }

app/views/dashboard/explore.html.haml
.container
  %h2
    Categories
    %small explore your solutions (here will be suggestions in a few days)
  .categories-list
    .tabbable.tabs-left
      %ul.nav.nav-tabs
        - i = 0
        - @categories.each do |category|
          %li{ class: (i += 1) == 1 && "active" }
            %a{ href: "#category#{category.id}", data: { toggle: "tab" } }= category.name
      .tab-content
        - i = 0
        - @categories.each do |category|
          .tab-pane{ class: (i += 1) == 1 && "active", id: "category#{category.id}" }
            %ul
              - @entries.select{|e| e.category_id == category.id}.each do |user_entry|
                %li.entry
                  = link_to user_entry.entry.title, user_entry.entry.url
                  %small.muted= user_entry.entry.description

app/views/dashboard/index.html.haml
.container
  %h2
    Smartfield
    %small the place where magic happens
  = form_tag search_entries_path(format: :json), method: :get, remote: true, class: "white form-search", id: "search-form" do
    %input.input-xxlarge.search-query#search-field{ name: 'q', type: "text", placeholder: "Enter search query or paste link started with http:// ot https:// to create a new entry." }

  #new-entry-container
    %h2 New entry
    .new-entry
      = form_tag entries_path(format: :json), remote: true, class: "form-horizontal", id: "new-entry-form" do
        %input{ type: "hidden", name: "entry[url]", id: "entry-url" }
        .control-group
          %label.control-label{ for: "entry-title" } Title
          .controls
            %input.input-xxlarge{ type: "text", name: "entry[title]", id: "entry-title" }
        .control-group
          %label.control-label{ for: "entry-description" } Description
          .controls
            %textarea.input-xxlarge{ name: "entry[description]", id: "entry-description", rows: 5 }
        .control-group
          %label.control-label Type
          .controls
            %label.radio
              %input{ type: "radio", name: "entry[type]", value: "gist" }
              Gist
            %label.radio
              %input{ type: "radio", name: "entry[type]", value: "gem" }
              Gem
            %label.radio
              %input{ type: "radio", name: "entry[type]", value: "screencast" }
              Screencast
            %label.radio
              %input{ type: "radio", name: "entry[type]", value: "article" }
              Article
        .control-group
          %label.control-label{ for: "entry-categories" } Categories
          .controls
            %input.input-xxlarge{ type: "text", name: "entry[categories]", id: "entry-categories" }
            %span.help-block Coma-separated
        .form-actions
          %input.btn.btn-primary.btn-large{ type: "submit", value: "Create entry" }

  #search-results-container
    %h2 Search results
    #search-results
    #nothing-found
      %h3.align-center Nothing found. In a few days we will have ability to show suggested results.
    .search-result-template
      .search-result.entry
        %h4.title
          %a.url{ href: '#', target: '_blank' }
          = link_to '#', method: :delete, remote: true, class: "close entry-destroy-link" do
            &times;
        %p.description
        %p.categories

  %p &nbsp;
  = render "recent"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta(charset='utf8')
    %title My Ruby Toolbox
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render "layouts/shared/navbar"
    = yield
    = javascript_include_tag "http://s0.railsrumble.com/banner.js"

app/views/layouts/shared/_navbar.html.haml
.navbar.navbar-static-top
  .navbar-inner
    .container
      = link_to "My Ruby Toolbox", root_path, class: "brand"
      .navbar-content
        %ul.nav
          %li{ class: params[:action] == "home" && "active" }= link_to "About", root_path
          - if user_signed_in?
            %li{ class: controller_name == "dashboard" && action_name == "index" && "active" }= link_to "Dashboard", dashboard_path
            %li{ class: controller_name == "dashboard" && action_name == "explore" && "active" }= link_to "Explore", explore_path
        - if user_signed_in?
          %ul.nav.pull-right
            %li.dropdown
              = link_to '#', data: { toggle: "dropdown" }, class: "dropdown-toggle" do
                = image_tag(current_user.avatar_url, class: "avatar") if current_user.avatar_url.present?
                = current_user.nick_and_name
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'ficon-logout'

app/views/pages/home.html.haml
.container
  .hero-unit
    %object.well(data="/assets/r150.svg" type="image/svg+xml")
    %h1 My Ruby Toolbox
    %p Collect explore and share your development experience
    %p Every time, when you start a new project or get a new task you need to remember how to do it. What libs are suitable? Where have I seen this tutorial? I've did the same thing already, where it was? We are tired of this and want to gather all of our experience in one place. So, if you share our thoughts – sign in and start collecting your knowledge!
    - unless user_signed_in?
      %p
        = link_to user_omniauth_authorize_path(:github), class: "btn btn-large btn-primary" do
          %span.btn-label
            %i.ficon-github
            Sign in via Github
  .row
    .span4
      %h2
        %i.ficon-inbox
        Collect
      %p
        Just paste link to gem, gist, screencast or article, add comment and you
        will be able to access your solutions base anytime and everywhere.
    .span4
      %h2
        %i.ficon-search
        Explore
      %p
        You didn't have a solution for task you work on? Not a problem! We will
        suggest you relevant solutions from another users.
    .span4
      %h2
        %i.ficon-export
        Share
        %small coming soon
      %p
        Your may mark your solutions as "shareable" to allow other users of "My
        Ruby Toolbox" access your knowledge and improve their skills.
.container
  %h1.align-center #{User.count} users added #{Entry.count} solutions to our database
  %p
    %br
- unless user_signed_in?
  .container
    .row
      .span4.offset4
        = link_to user_omniauth_authorize_path(:github), class: "btn btn-large btn-primary btn-block" do
          %span.btn-label
            %i.ficon-github
            Sign in and start using!